### ISSUE TITLE
 رعایت کپی رایت توسط اپلیکیشن بلد 

### ISSUE THREAD

**Issue by imanmoghimiq30** [IranOSM-Monitor/IranOSM-Monitor-DB#5]
بلد در نسخه 2.0.5 به طور کامل کپی رایت رو رعایت کرده

**Comment by ahangarha** [comment]
<div dir=rtl>
ممنون بابت اطلاع

به نظر می‌رسد از تاریخ ۱۶ بهمن، این تغییرات اعمال شده باشد.

![image](https://user-images.githubusercontent.com/11241315/52716953-2baf3700-2fb5-11e9-9ee5-cdc04a896698.png)
